export const themes = [
  {
    label: "Alert",
    value: 0,
    img: "https://templates.bplugins.com/wp-content/uploads/2025/10/warning.png",
    height: "auto",
    width: "160px",
    isPro: false,
  },
  {
    label: "Error",
    value: 1,
    img: "https://templates.bplugins.com/wp-content/uploads/2025/10/error.png",
    height: "auto",
    width: "160px",
    isPro: false,
  },
  {
    label: "Info-URL",
    value: 2,
    img: "https://templates.bplugins.com/wp-content/uploads/2025/10/info-btn.png",
    height: "auto",
    width: "160px",
    isPro: false,
  },
  {
    label: "Info-Bookmark",
    value: 3,
    img: "https://templates.bplugins.com/wp-content/uploads/2025/10/info-bookmark.png",
    height: "auto",
    width: "160px",
    isPro: false,
  },
  {
    label: "Info-Basic",
    value: 4,
    img: "https://templates.bplugins.com/wp-content/uploads/2025/10/info.png",
    height: "auto",
    width: "160px",
    isPro: false,
  },
  {
    label: "Admin Settings",
    value: 5,
    img: "https://templates.bplugins.com/wp-content/uploads/2025/10/admin-settings.png",
    height: "auto",
    width: "160px",
    isPro: false,
  },
  {
    label: "Admin Info",
    value: 6,
    img: "https://templates.bplugins.com/wp-content/uploads/2025/10/admin-info.png",
    height: "auto",
    width: "160px",
    isPro: false,
  },
  {
    label: "Admin-Permission",
    value: 7,
    img: "https://templates.bplugins.com/wp-content/uploads/2025/10/admin-permission.png",
    height: "auto",
    width: "160px",
    isPro: false,
  },
  {
    label: "Admin Alert",
    value: 8,
    img: "https://templates.bplugins.com/wp-content/uploads/2025/10/admin-alert.png",
    height: "auto",
    width: "160px",
    isPro: false,
  },
  {
    label: "File",
    value: 9,
    img: "https://templates.bplugins.com/wp-content/uploads/2025/10/file.png",
    height: "auto",
    width: "160px",
    isPro: false,
  },
  {
    label: "Tip",
    value: 10,
    img: "https://templates.bplugins.com/wp-content/uploads/2025/10/tip.png",
    height: "auto",
    width: "160px",
    isPro: false,
  },
];
